#! /bin/bash

# Check to ensure numpy is installed
exitval=0
module="numpy"
cat >tmp_bootstrap.py<< EOF
try:
    import $module
    exit(0)
except ImportError:
    exit(1)
EOF
if python -m tmp_bootstrap
then
    echo "INFO: Found $module"
else
    echo "ERROR: Missing $module"
    echo "INFO: attempting to install $module via pip"
    echo "INFO: pip install $module"
    pip install $module
    exitval=$?
fi
rm tmp_bootstrap.py
if [ $exitval -eq 0 ]
then
    echo "INFO: Good to go!"
else
    echo "WARNING: Not good to go!"
fi
exit $exitval
